config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    resources :homes
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  # 顧客側ルーティング
  scope module: :public do
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show] do
      collection do
        get :search
        get :genre_search
      end
    end

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: "cart_items_destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]


    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update,]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:update, :show]
    resources :orders_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  validates :amount, presence: true
  
  validates :amount, presence: true, numericality: { greater_than: 0 }
  
  def subtotal
    item.with_tax_price * amount
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー]+\z/}
  validates :email, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true
         
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
   
   has_many :cart_items, dependent: :destroy
   has_many :order_ditails, dependent: :destroy
   belongs_to :genre, dependent: :destroy
   
   has_one_attached :image
   validates :name, {presence: true}
   validates :introduction, {presence: true}
   validates :price, {presence: true}
   validates :genre, {presence: true}
   
   def get_image
      (image.attached?) ? image : 'no_image.jpg'
   end
   
   def with_tax_price
      tax_rate = 0.1
      price * (1 + tax_rate)
   end
   
   def display_price
      with_tax_price.floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, dependent: :destroy
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, dependent: :destroy
  belongs_to :item, dependent: :destroy
  
  enum making_status: { not_started: 0, awaiting_manufacture: 1, under_manufacture: 2, completion_of_manufacturing: 3 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path ,notice: "登録しました"
    else
      @genres = Genre.all
      render 'index'
    end
  end
  
  def show
    @genre = Genre.find(params[:id])
    @items = @genre.items
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "変更を保存しました。"
    else
      render 'edit'
    end     
  end
  
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    # @orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end
  
  def about
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品が作成されました"
    else
      redirect_to new_admin_item_path, alert: "商品の作成に失敗しました"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品が更新されました"
    else
      redirect_to edit_admin_item_path(@item), alert: "商品の更新に失敗しました"
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :introduction, :price, :is_active, :genre_id, :name)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      @order_details.update_all(making_status: "awaiting_manufacture") if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order), notice: "注文ステータスを「" + @order.status_i18n + "」に更新しました。"
  end

  private

  def order_params

    params.require(:order).permit(:status)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_genres
  
  private
  
  def set_genres
    @genres = Genre.all
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="my-4 ml-4">ジャンル編集</h3> 
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-start">
    <div class="col-md-6">
      <%= form_with model: @genre, url: admin_genre_path(@genre), local: true do |f| %>
        <div class="form-group d-flex align-items-center">
          <%= f.label :name, "ジャンル名", class: "mr-3" %>
          <%= f.text_field :name, class: "form-control mr-3", placeholder: "ジャンル名", style: "width: 200px;" %>
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h4 class="my-4">ジャンル一覧・追加</h4>
  
  <div class="row mb-4">
    <div class="col">
      <%= form_with model: @genre, url: admin_genres_path, local: true, class: "form-inline" do |f| %>
        <div class="form-group mr-2">
          <%= f.label :name, "ジャンル名", class: "mr-2" %>
          <%= f.text_field :name, class: "form-control mr-2", placeholder: "ジャンル名" %>
        </div>
        <%= f.submit "新規登録", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td class="text-center"><%= link_to '編集する', edit_admin_genre_path(genre), class: "btn btn-success btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-5 col-xs-5">
      <h4>商品編集</h4>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6 px-sm-0 offset-3">
      <%= form_with model: @item, url: admin_item_path(@item), local: true, method: :patch do |f| %>
        <table class="table table-borderless table-sm mx-auto">
          
          <tr>
            <th><%= f.label :商品画像 %></th>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          
          <tr>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名", class: "form-control" %></td>
          </tr>
          
          <tr>
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, placeholder:"ここに説明文を記述します", class: "form-control", rows: 5 %></td>
          </tr>
          
          <tr>
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "ジャンルを選択してください" }, { class: "form-control" } %></td>
          </tr>
          
          <tr>
            <th><%= f.label :税抜価格 %></th>
            <td><%= f.text_field :price, placeholder:"1000", :size => "50" %>円</td>
          </tr>
          
          <tr>
            <th><%= f.label :is_active, "販売ステータス" %></th>
            <td>
              <div class="d-flex justify-content-center">
                <div class="form-check form-check-inline mr-5">
                  <%= f.radio_button :is_active, true, class: "form-check-input" %>
                  <%= f.label :is_active, "販売中", class: "form-check-label" %>
                </div>
                <div class="form-check form-check-inline">
                  <%= f.radio_button :is_active, false, class: "form-check-input" %>
                  <%= f.label :is_active, "販売停止中", class: "form-check-label" %>
                </div>
              </div>
            </td>
          </tr>
          
          <tr>
            <td colspan="2" class="text-center">
              <%= f.submit "更新", class:"btn btn-success" %>
            </td>
          </tr>
          
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1 my-2">
      <h4>商品一覧</h4>
    </div>
    <div class="col-sm-2 px-sm-0 text-right my-2">
      <%= link_to "商品新規登録", new_admin_item_path, class:"btn btn-success" %>
    </div>
  </div>
  
  <div class="row">
    <table class="table table-borderless table-sm" >
      
      <thead class="thead-light">
        <tr>
          <th style="width: 8%">商品ID</th>
          <th style="width: 35%">商品名</th>
          <th style="width: 15%">税抜価格</th>
          <th style="width: 25%">ジャンル</th>
          <th style="width: 17%">ステータス</th>
        </tr>
      </thead>
      
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item) %></td>
          <td><%= item.price.to_s(:delimited, delimiter: ',') %></td>
          <td><%= item.genre.name %></td>
          <th>
            <% if item.is_active %>
            <p class="text-success">販売中</p>
            <% else %>
            <p class="text-black-50">販売停止中</p>
            <% end %>
          </th>
        </tr>
        <% end %>
      </tbody>
      
      <tfoot>
        <tr>
          <th colspan="2"></th>
          <td>
            <%= paginate @items %>
          </td>
        </tr>
      </tfoot>
      
    </table>
  </div>
  
</div>

app/views/admin/items/new.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-5 col-xs-5 my-2">
      <h4 class="text-center">商品新規登録</h4>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6 px-sm-0 offset-3">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
        <table class="table table-borderless table-sm">
          
          <tr>
            <th><%= f.label :商品画像 %></th>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          
          <tr>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名", class: "form-control" %></td>
          </tr>
          
          <tr>
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, placeholder:"ここに説明文を記述します", class: "form-control", rows: 5 %></td>
          </tr>
          
          <tr>
            <th><%= f.label :ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "ジャンルを選択してください" }, { class: "form-control" } %></td>
          </tr>
          
          <tr>
            <th><%= f.label :税抜価格 %></th>
            <td><%= f.text_field :price, placeholder:"1000", :size => "50" %>円</td>
          </tr>
          
          <tr>
            <th><%= f.label :is_active, "販売ステータス" %></th>
            <td>
              <div class="d-flex justify-content-center">
                <div class="form-check form-check-inline mr-5">
                  <%= f.radio_button :is_active, true, checked: true, class: "form-check-input" %>
                  <%= f.label :is_active, "販売中", class: "form-check-label" %>
                </div>
                <div class="form-check form-check-inline">
                  <%= f.radio_button :is_active, false, class: "form-check-input" %>
                  <%= f.label :is_active, "販売停止中", class: "form-check-label" %>
                </div>
              </div>
            </td>
          </tr>
          
          <tr>
            <td colspan="2" class="text-center">
              <%= f.submit "新規登録", class:"btn btn-success" %>
            </td>
          </tr>
          
        </table>
      <% end %>
    </div>
    
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-4">
      <h4>商品詳細</h4>
      <% if @item %>
        <%= image_tag @item.get_image, size: "300x200" %>
      <% else %>
        <%= image_tag "no_image.jpg" %>
      <% end %>
    </div>

    <div class="col-xs-8">
      <table class="table table-borderless">

        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>

        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>

        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>

        <tr>
          <td>税込価格<br>(税抜価格)</td>
          <td><%= @item.with_tax_price.floor.to_s(:delimited, delimiter: ',') %>（<%= @item.price.to_s(:delimited, delimiter: ',') %>）円</td>
        </tr>

        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active %>
            <p class="text-success">販売中</p>
            <% else %>
            <p class="text-danger">販売停止中</p>
            <% end %>
          </td>
        </tr>

        <tr>
          <td colspan="2" class="text-center">
            <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
          </td>
        </tr>

      </table>
    </div>

  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 my-5">
      <h4>注文履歴詳細</h4>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_root_path do %>
              <%= @order.customer.full_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postal_code.to_s.insert(3, "-") %> <%= @order.address %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= @order.name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |t| %>
              <%= t.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>
              <%= t.submit "更新", class: "btn btn-success ml-5" %>
            <% end %>
          </td>
        </tr>
      </table>
        <div class="row">
        <div class="col-9">
          <table class="table table-borderless">
            <thead class="table-secondary">
              <tr>
                <th>商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
                <th>製作ステータス</th>
                <th></th>
              </tr>
            </thead>
            <% @order_details.each do |t| %>
              <tbody>
                <tr>
                  <td><%= t.item.name %></td>
                  <td><%= t.item.display_price.to_s(:delimited, delimiter: ',') %></td>
                  <td><%= t.amount %></td>
                  <td><%= (t.item.display_price*t.amount).to_s(:delimited, delimiter: ',') %></td>
                  <td>
                    <%= form_with model: t, url: admin_orders_detail_path(t), method: :patch, local: true do |f| %>
                      <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                      <%= f.submit "更新", class: "btn btn-success ml-5" %>
                    <% end %>
                  </td>
                </tr>
              </tbody>
            <% end %>
          </table>
            </div>
        <div class="col-3">
          <table class="table table-borderless">
            <tr>
              <th>商品合計</th>
              <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= @order.shipping_cost.to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
            <tr>
              <th>請求金額合計</th>
              <td><%= @order.total_payment.to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>