config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    resources :homes
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  # 顧客側ルーティング
  scope module: :public do
    get 'about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    resources :items, only: [:index, :show] do
      collection do
        get :search
        get :genre_search
      end
    end

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: "cart_items_destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:new, :create, :index, :show]


    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update,]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:update, :show]
    resources :orders_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :customer
  
  validates :amount, presence: true
  
  validates :amount, presence: true, numericality: { greater_than: 0 }
  
  def subtotal
    item.with_tax_price * amount
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー]+\z/}
  validates :email, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true
         
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
   
   has_many :cart_items, dependent: :destroy
   has_many :order_ditails, dependent: :destroy
   belongs_to :genre, dependent: :destroy
   
   has_one_attached :image
   validates :name, {presence: true}
   validates :introduction, {presence: true}
   validates :price, {presence: true}
   validates :genre, {presence: true}
   
   def get_image
      (image.attached?) ? image : 'no_image.jpg'
   end
   
   def with_tax_price
      tax_rate = 0.1
      price * (1 + tax_rate)
   end
   
   def display_price
      with_tax_price.floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, dependent: :destroy
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, dependent: :destroy
  belongs_to :item, dependent: :destroy
  
  enum making_status: { not_started: 0, awaiting_manufacture: 1, under_manufacture: 2, completion_of_manufacturing: 3 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    # @orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end
  
  def about
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品が作成されました"
    else
      redirect_to new_admin_item_path, alert: "商品の作成に失敗しました"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品が更新されました"
    else
      redirect_to edit_admin_item_path(@item), alert: "商品の更新に失敗しました"
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :introduction, :price, :is_active, :genre_id, :name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_genres
  
  private
  
  def set_genres
    @genres = Genre.all
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer style="padding-top: 70px; background-color: #f7d358;">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>

    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg", style="background-color: #f5da81; color: black;">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text-dark">ながのCake</span></a>
      <div class="mx-auto">
        <% if customer_signed_in? %>
          <span>ようこそ、<%= current_customer.full_name %>さん！</span>
        <% end %>
      </div>
      <div class="ml-auto">
        <div class="links">
          <ul class="navbar-nav">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to customers_my_page_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-home"></i> マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to items_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-cheese"></i></i> 商品一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to cart_items_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-cart-shopping"></i> カート
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_customer_session_path, class: 'nav-link text-dark', method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_customers_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-user-circle"></i> 会員一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_items_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-cheese"></i></i> 商品一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_root_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-clipboard"></i></i> 注文履歴一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
                  <i class="fa-solid fa-rectangle-list"></i></i> ジャンル一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, class: 'nav-link text-dark', method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-link text"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to items_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-cheese"></i></i> 商品一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_registration_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-user-plus"></i></i> 新規登録
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_session_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="search-box float-right">
          <%= form_tag(search_items_path, method: :get, class: "form-inline") do %>
            <%= text_field_tag :content, params[:query], class: "form-control mr-sm-2", placeholder: "商品検索", aria: { label: "Search" } %>
            <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          <% end %>

        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/21474bdd09.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/header' %>
    <main class="flex-grow-1">
      <% if flash[:notice] %>
        <div class="alert alert-success text-center"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger text-center"><%= flash[:alert] %></div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>